name: reverseqr
services:
  client:
    image: httpd
    ports:
      - "${CLIENT_PORT}:80"
    volumes:
      - "./client/:/usr/local/apache2/htdocs/"
      - "./.env:/usr/local/apache2/htdocs/.env"
    restart: always
  server:
    build: "./server/"
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - "./server/:/app"
